//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPHE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pheEntities : DbContext
    {
        public pheEntities()
            : base("name=pheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> UsuariosSet { get; set; }
        public virtual DbSet<Cursos> CursosSet { get; set; }
        public virtual DbSet<Usuarios_Cursos> Usuarios_CursosSet { get; set; }
        public virtual DbSet<Lugares> LugaresSet { get; set; }
        public virtual DbSet<Genero> GeneroSet { get; set; }
        public virtual DbSet<Modalidades> ModalidadesSet { get; set; }
        public virtual DbSet<TipoCursos> TipoCursosSet { get; set; }
        public virtual DbSet<Categorias> CategoriasSet { get; set; }
        public virtual DbSet<LineasCarreras> LineasCarrerasSet { get; set; }
    }
}
