//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPHE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Usuarios_CursosSet = new HashSet<Usuarios_Cursos>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nombres")]
        public string nombres { get; set; }
        [Display(Name = "Apellidos")]
        public string apellidos { get; set; }
        [Display(Name = "Fecha de Nacimiento")]
        public System.DateTime fec_nac { get; set; }
        [Display(Name = "Lugar de Nacimiento")]
        public int id_lug_nac { get; set; }
        [Display(Name = "Lugar de Residencia")]
        public int id_lug_res { get; set; }
        [Display(Name = "Genero")]
        public int id_genero { get; set; }
        [Display(Name = "Hobbies")]
        public string hobbies { get; set; }
    
        public virtual Genero GeneroSet { get; set; }
        public virtual Lugares LugaresNacSet { get; set; }
        public virtual Lugares LugaresResSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Cursos> Usuarios_CursosSet { get; set; }
    }
}
